name: Go

on:
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Publish package
      run: |
        GOPROXY=proxy.golang.org go list -m github.com/woxingliu/rice@${GITHUB_REF#refs/*/}
        curl -X POST https://pkg.go.dev/fetch/github.com/woxingliu/rice@${GITHUB_REF#refs/*/}
